services:
  - type: web
    name: 'rari-demo'
    runtime: node
    env: node
    plan: free
    buildCommand: '{{INSTALL_COMMAND}}'
    startCommand: 'pnpm start'
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: RUST_LOG
        value: info
